import { ArrowLeft } from 'lucide-react';
import { Button } from './ui/button';
import { useState, useEffect } from 'react';
import { haptics } from '../utils/haptics';

interface PrivacyPageProps {
  onNavigate: (page: string) => void;
  isAuthenticated?: boolean;
}

export function PrivacyPage({ onNavigate, isAuthenticated = true }: PrivacyPageProps) {
  const [isDesktop, setIsDesktop] = useState(false);

  useEffect(() => {
    const checkDesktop = () => {
      setIsDesktop(window.innerWidth >= 1024);
    };
    
    checkDesktop();
    window.addEventListener('resize', checkDesktop);
    return () => window.removeEventListener('resize', checkDesktop);
  }, []);

  const handleBack = () => {
    haptics.light();
    if (!isAuthenticated) {
      onNavigate('login');
    } else if (isDesktop) {
      onNavigate('dashboard');
    } else {
      onNavigate('settings');
    }
  };

  return (
    <div className="min-h-screen bg-white dark:bg-[#000000] flex flex-col">
      <div className="flex-1 max-w-4xl mx-auto px-6 py-12 w-full">
        <div className="flex items-start gap-4 mb-8">
          <button
            onClick={handleBack}
            className="text-gray-900 dark:text-white hover:text-[#ec1e24] p-2 -ml-2 mt-1"
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round">
              <path d="M22 12H2M9 19l-7-7 7-7"/>
            </svg>
          </button>
          <h1 className="text-2xl text-gray-900 dark:text-white">Privacy Policy</h1>
        </div>
        
        <div className="bg-white dark:bg-[#000000] border border-gray-200 dark:border-[#333333] p-6 rounded-2xl space-y-4 text-gray-700 dark:text-[#D1D5DB]">
          <p>
            Screndly collects data necessary to provide video generation and automation services. The platform stores account information, usage logs, media files generated by the user, API events, and billing records. Screndly does not sell personal data. Data is processed to operate core features, improve system performance, maintain security, and comply with legal and payment requirements.
          </p>
          
          <h3 className="text-gray-900 dark:text-white mt-6 mb-2">Meta Platform Integration</h3>
          <p>
            When you connect your Facebook Page and Instagram Business account to Screndly, we access and store OAuth tokens to publish content on your behalf. This includes:
          </p>
          <ul className="list-disc list-inside space-y-1 ml-4">
            <li>Access tokens for Facebook and Instagram API access</li>
            <li>Your Facebook Page ID and Instagram Business Account ID</li>
            <li>Publishing activity logs and quota usage</li>
            <li>Video metadata and captions for automated posting</li>
          </ul>
          <p>
            We use the following Meta permissions: instagram_basic, instagram_content_publish, instagram_manage_insights, pages_read_engagement, pages_show_list, pages_manage_posts, pages_manage_metadata, pages_read_user_content, publish_video, and business_management. These permissions allow Screndly to publish video content and monitor engagement on your connected accounts.
          </p>
          <p>
            All Meta OAuth tokens are encrypted using AES-256-GCM encryption and stored securely. Tokens are only used to perform actions you have explicitly authorized through the Screndly dashboard. You can revoke Screndly's access to your Meta accounts at any time through the Settings page or through your Facebook account settings at <a href="https://www.facebook.com/settings?tab=business_tools" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">facebook.com/settings?tab=business_tools</a>.
          </p>
          <p>
            Screndly complies with Meta's Platform Terms and Developer Policies. We do not store or access personal data from your followers, and we only publish content that you have explicitly configured through RSS feeds or manual uploads. For more information about how Meta handles your data, please review Meta's Privacy Policy at <a href="https://www.facebook.com/privacy/policy" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">facebook.com/privacy/policy</a>.
          </p>
          
          <h3 className="text-gray-900 dark:text-white mt-6 mb-2">X (Twitter) Platform Integration</h3>
          <p>
            When you connect your X (Twitter) account to Screndly, we access and store OAuth 2.0 tokens to publish content on your behalf. This includes:
          </p>
          <ul className="list-disc list-inside space-y-1 ml-4">
            <li>Access tokens and refresh tokens for X API access</li>
            <li>Your X account ID and username</li>
            <li>Tweet publishing activity logs and quota usage</li>
            <li>Video upload metadata and processing status</li>
            <li>Daily and monthly tweet count tracking</li>
          </ul>
          <p>
            We use the following X API scopes: tweet.read (read tweets), tweet.write (create and publish tweets), users.read (access basic user information), and offline.access (maintain refresh tokens). These permissions allow Screndly to publish video content to your X account and track usage quotas based on your API tier (Free, Basic, Pro, or Enterprise).
          </p>
          <p>
            All X OAuth tokens are encrypted using AES-256-GCM encryption with PKCE (Proof Key for Code Exchange) for enhanced security. Tokens are only used to perform actions you have explicitly authorized through the Screndly dashboard. You can revoke Screndly's access to your X account at any time through the Settings page or through your X account settings at <a href="https://twitter.com/settings/connected_apps" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">twitter.com/settings/connected_apps</a>.
          </p>
          <p>
            Screndly implements chunked video upload (INIT/APPEND/FINALIZE) as specified by X API documentation. Videos are uploaded directly to X servers and are not stored on Screndly infrastructure beyond temporary processing. We track your API tier limits (Free: 50 tweets/day, Basic: 3,000/day, Pro: 10,000/day, Enterprise: 100,000/day) to prevent exceeding your account quotas. All usage tracking is stored locally and encrypted.
          </p>
          <p>
            Screndly complies with X's Developer Agreement and Policy. We do not access or store any data from your followers, mentions, or direct messages. We only publish content that you have explicitly configured through RSS feeds, manual uploads, or test publishing. For more information about how X handles your data, please review X's Privacy Policy at <a href="https://twitter.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">twitter.com/privacy</a>.
          </p>
          
          <h3 className="text-gray-900 dark:text-white mt-6 mb-2">TikTok Platform Integration</h3>
          <p>
            When you connect your TikTok account to Screndly, we access and store OAuth 2.0 tokens to publish content on your behalf. This includes:
          </p>
          <ul className="list-disc list-inside space-y-1 ml-4">
            <li>Access tokens and refresh tokens for TikTok API access</li>
            <li>Your TikTok Open ID and user profile information</li>
            <li>Video upload activity logs and processing status</li>
            <li>Daily and hourly post count tracking for rate limiting</li>
            <li>Video metadata including titles, privacy settings, and interaction preferences</li>
          </ul>
          <p>
            We use the following TikTok API scopes: user.info.basic (access basic user profile), video.publish (publish video content), and video.upload (upload video files). These permissions allow Screndly to publish video content to your TikTok account while respecting TikTok's recommended posting limits (maximum 5 posts per day, 1 hour between posts).
          </p>
          <p>
            All TikTok OAuth tokens are encrypted using AES-256-GCM encryption and stored securely. Tokens are only used to perform actions you have explicitly authorized through the Screndly dashboard. You can revoke Screndly's access to your TikTok account at any time through the Settings page or through your TikTok account settings at <a href="https://www.tiktok.com/setting/privacy-and-safety" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">tiktok.com/setting/privacy-and-safety</a>.
          </p>
          <p>
            Screndly uploads videos directly to TikTok servers using TikTok's Content Posting API. Videos are not stored on Screndly infrastructure beyond temporary processing required for upload. We track your posting activity to prevent exceeding TikTok's rate limits (5 posts/day, 1 post/hour) and to avoid spam detection. All usage tracking is stored locally and encrypted.
          </p>
          <p>
            <strong>TikTok App Verification:</strong> Screndly's TikTok integration requires app verification approval from TikTok. Before production use, our app undergoes TikTok's review process for Login Kit and Content Posting API access. During this review, TikTok evaluates our use case, implementation, and compliance with their Developer Terms. Users can only connect their TikTok accounts after our app has been approved by TikTok.
          </p>
          <p>
            Screndly complies with TikTok's Developer Terms and Community Guidelines. We do not access or store any data from your followers, comments, or direct messages. We only publish content that you have explicitly configured through RSS feeds, manual uploads, or test publishing. For more information about how TikTok handles your data, please review TikTok's Privacy Policy at <a href="https://www.tiktok.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">tiktok.com/legal/privacy-policy</a>.
          </p>
          
          <h3 className="text-gray-900 dark:text-white mt-6 mb-2">YouTube Platform Integration</h3>
          <p>
            When you connect your YouTube channel to Screndly, we access and store OAuth 2.0 tokens to upload content on your behalf. This includes:
          </p>
          <ul className="list-disc list-inside space-y-1 ml-4">
            <li>Access tokens and refresh tokens for YouTube Data API access</li>
            <li>Your YouTube channel ID, name, and basic profile information</li>
            <li>Video upload activity logs and processing status</li>
            <li>Daily quota usage tracking (uploads, metadata updates, playlist operations)</li>
            <li>Video metadata including titles, descriptions, tags, categories, and privacy settings</li>
          </ul>
          <p>
            We use the following YouTube API scopes: youtube.upload (upload videos), youtube (manage YouTube account), and youtube.force-ssl (secure API access). These permissions allow Screndly to upload video content to your YouTube channel with complete metadata control.
          </p>
          <p>
            All YouTube OAuth tokens are encrypted using AES-256-GCM encryption with PKCE (Proof Key for Code Exchange) for enhanced security. Tokens are only used to perform actions you have explicitly authorized through the Screndly dashboard. You can revoke Screndly's access to your YouTube channel at any time through the Settings page or through your Google Account settings at <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">myaccount.google.com/permissions</a>.
          </p>
          <p>
            Screndly uploads videos directly to YouTube servers using YouTube's resumable upload protocol (INIT/UPLOAD chunks/FINALIZE). Videos are not stored on Screndly infrastructure beyond temporary processing required for upload. We track your YouTube API quota usage to prevent exceeding the default limit of 10,000 units per day (approximately 6 video uploads per day). All usage tracking is stored locally and encrypted.
          </p>
          <p>
            <strong>YouTube API Quota Management:</strong> The YouTube Data API v3 uses a quota system where each operation costs "units." Video uploads cost 1,600 units each. With the default quota of 10,000 units per day, you can upload approximately 6 videos per day. Quota resets daily at midnight Pacific Time. You can request a quota increase through the Google Cloud Console if you need to upload more frequently.
          </p>
          <p>
            <strong>Google Cloud Verification:</strong> Screndly's YouTube integration requires OAuth consent screen verification for public use. Before production use, our app undergoes Google's verification process for OAuth scopes. During this review, Google evaluates our use case, privacy policy, and compliance with their API Services User Data Policy. Unverified apps are limited to 100 test users.
          </p>
          <p>
            Screndly complies with Google's API Services User Data Policy and YouTube Terms of Service. We do not access or store any data from your channel subscribers, comments, or analytics beyond what is necessary for upload operations. We only upload content that you have explicitly configured through RSS feeds, manual uploads, or test publishing. For more information about how YouTube handles your data, please review YouTube's Privacy Policy at <a href="https://www.youtube.com/howyoutubeworks/our-commitments/protecting-user-data/" target="_blank" rel="noopener noreferrer" className="text-[#ec1e24] hover:underline">youtube.com/howyoutubeworks/protecting-user-data</a>.
          </p>
          
          <h3 className="text-gray-900 dark:text-white mt-6 mb-2">Third-Party Services</h3>
          <p>
            Third parties involved in infrastructure—such as hosting, storage, and analytics providers—may access data only to the extent required to operate the service. Users may request data export or deletion unless retention is required for fraud prevention or legal compliance.
          </p>
          
          <h3 className="text-gray-900 dark:text-white mt-6 mb-2">Security & Access Control</h3>
          <p>
            Access to the dashboard requires authentication and actions are logged for security. Screndly uses cookies and session data to maintain login state and prevent abuse. Continued use of the platform constitutes consent to this policy.
          </p>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-gray-200 dark:border-[#374151] py-8 px-6 mt-12">
        <div className="max-w-4xl mx-auto space-y-4">
          <div className="flex flex-wrap gap-2 justify-center text-sm text-gray-600 dark:text-[#9CA3AF]">
            <button onClick={() => onNavigate('privacy')} className="hover:text-[#ec1e24]">Privacy</button>
            <span>•</span>
            <button onClick={() => onNavigate('terms')} className="hover:text-[#ec1e24]">Terms</button>
            <span>•</span>
            <button onClick={() => onNavigate('disclaimer')} className="hover:text-[#ec1e24]">Disclaimer</button>
            <span>•</span>
            <button onClick={() => onNavigate('cookie')} className="hover:text-[#ec1e24]">Cookie</button>
            <span>•</span>
            <button onClick={() => onNavigate('contact')} className="hover:text-[#ec1e24]">Contact</button>
            <span>•</span>
            <button onClick={() => onNavigate('about')} className="hover:text-[#ec1e24]">About</button>
          </div>
          <p className="text-center text-sm text-gray-600 dark:text-[#9CA3AF]">
            ©️ 2026, Screndly. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}